ALTER TABLE products
  ADD COLUMN IF NOT EXISTS slide_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS slide_title TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS slide_subtitle TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS slide_order INTEGER NOT NULL DEFAULT 0;
