import PDFDocument from 'pdfkit'

const CREAM='#f3efe7'; const INK='#171816'; const OXIDE='#b5532d'; const MUTED='#716d65'; const LINE='#d1c8bb'

function money(value,currency){return new Intl.NumberFormat('es-UY',{style:'currency',currency:currency||'USD',maximumFractionDigits:2}).format(Number(value||0))}
function footer(doc,page){doc.strokeColor(LINE).lineWidth(.6).moveTo(48,792).lineTo(547,792).stroke();doc.fillColor(MUTED).font('Helvetica').fontSize(7).text('contacto@mercadobra.com  |  +598 99 213 300  |  Montevideo, Uruguay',48,802);doc.text(String(page).padStart(2,'0'),520,802,{width:27,align:'right'})}
function brand(doc,label){doc.fillColor(INK).font('Helvetica-Bold').fontSize(22).text('OXI',48,42,{continued:true});doc.fillColor(OXIDE).text('D',{continued:true});doc.fillColor(INK).text('A');doc.font('Helvetica').fontSize(8).text('S T U D I O',54,69);doc.font('Helvetica-Bold').fontSize(22).text(label,300,43,{width:247,align:'right'});doc.strokeColor(OXIDE).lineWidth(1.2).moveTo(48,96).lineTo(547,96).stroke()}
function background(doc){doc.rect(0,0,595.28,841.89).fill(CREAM);doc.save().opacity(.2).strokeColor('#b9ad9d').lineWidth(.5);for(let x=360;x<680;x+=55)doc.moveTo(x,0).lineTo(x-205,842).stroke();doc.restore()}
function section(doc,title,y){doc.fillColor(INK).font('Helvetica-Bold').fontSize(10).text(title.toUpperCase(),48,y);doc.strokeColor(OXIDE).lineWidth(1).moveTo(48,y+17).lineTo(547,y+17).stroke();return y+30}

export function createQuotePdf({quote,customer}){
  return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:0,info:{Title:`Cotizacion ${quote.referenceNumber}`,Author:'Oxida Studio by Mercadobra'}});const chunks=[];doc.on('data',chunk=>chunks.push(chunk));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)
    background(doc);brand(doc,'COTIZACION');
    doc.fillColor(OXIDE).font('Helvetica-Bold').fontSize(8).text('P R O P U E S T A   E C O N O M I C A',48,122);doc.fillColor(INK).fontSize(26).text(quote.title||'Proyecto',48,139,{width:499});
    const meta=[['CLIENTE',customer?.name||customer?.company||''],['COTIZACION',quote.referenceNumber||''],['FECHA',new Date().toLocaleDateString('es-UY')],['VALIDEZ',`${quote.documentTerms?.validityDays||30} dias`],['MONEDA',quote.currency||'USD']];let mx=48;meta.forEach(([label,value],index)=>{const w=index===0?190:72;doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(6).text(label,mx,190);doc.rect(mx,203,w,31).strokeColor(LINE).stroke();doc.fillColor(INK).font('Helvetica').fontSize(8).text(String(value),mx+7,214,{width:w-14,ellipsis:true});mx+=w+8})
    let y=264;doc.rect(48,y,499,28).fill(INK);doc.fillColor('#fff').font('Helvetica-Bold').fontSize(7).text('ITEM / ALCANCE',58,y+10);doc.text('SUBTOTAL',407,y+10,{width:125,align:'right'});y+=28
    const items=(quote.documentItems||[]).length?quote.documentItems:[{code:'01',description:quote.title,subtotal:Number(quote.totalAmount||0)/(1+Number(quote.taxRate||22)/100)}];items.slice(0,10).forEach((item,index)=>{const rowH=44;doc.rect(48,y,499,rowH).strokeColor(LINE).stroke();doc.fillColor(OXIDE).font('Helvetica-Bold').fontSize(7).text(item.code||String(index+1).padStart(2,'0'),58,y+9,{width:32});doc.fillColor(INK).fontSize(8).text(item.description||'',94,y+8,{width:300,height:28,ellipsis:true});doc.font('Helvetica-Bold').text(money(item.subtotal,quote.currency),407,y+15,{width:125,align:'right'});y+=rowH})
    const subtotal=items.reduce((sum,item)=>sum+Number(item.subtotal||0),0);const tax=subtotal*Number(quote.taxRate||0)/100;const total=subtotal+tax;y+=12;[['SUBTOTAL',subtotal],['IVA',tax],['TOTAL PROPUESTA',total]].forEach(([label,value],index)=>{const h=index===2?34:25;if(index===2)doc.rect(300,y,247,h).fill(INK);doc.fillColor(index===2?'#fff':MUTED).font('Helvetica-Bold').fontSize(index===2?9:7).text(`${label}${label==='IVA'?` (${quote.taxRate||0}%)`:''}`,312,y+9);doc.text(money(value,quote.currency),407,y+9,{width:125,align:'right'});y+=h})
    doc.fillColor(MUTED).font('Helvetica').fontSize(7).text('Importes expresados en la moneda indicada. Las condiciones esenciales se detallan en la pagina siguiente.',48,748,{width:499});footer(doc,1)
    doc.addPage();background(doc);brand(doc,'CONDICIONES');let ty=130;const terms=quote.documentTerms||{};const blocks=[['ALCANCE',quote.proposalDescription||quote.description||''],['FORMA DE PAGO',terms.paymentTerms||'Se establece segun la propuesta comercial y la sena indicada.'],['PLAZO DE EJECUCION',terms.executionTime||'A coordinar una vez aceptada la propuesta y confirmada la sena.'],['GARANTIA',terms.warranty||'12 meses por defectos de fabricacion, soldadura y montaje no atribuibles a mal uso.'],['EXCLUSIONES',terms.exclusions||'Cambios de alcance o especificacion posteriores a la aprobacion se cotizan como adicionales.'],['NOTAS',terms.notes||'']].filter(([,text])=>String(text).trim());for(const [title,text] of blocks){ty=section(doc,title,ty);doc.fillColor(INK).font('Helvetica').fontSize(9).text(String(text),48,ty,{width:499,lineGap:3});ty=doc.y+24;if(ty>690)break}
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(10).text('APROBACION DE LA PROPUESTA',48,690);doc.font('Helvetica').fontSize(8).text('Nombre, conformidad y fecha de aceptacion.',48,708);doc.strokeColor(MUTED).moveTo(48,756).lineTo(315,756).stroke();doc.moveTo(360,756).lineTo(547,756).stroke();doc.font('Helvetica-Bold').fontSize(6).text('NOMBRE / FIRMA',48,764);doc.text('FECHA',360,764);footer(doc,2);doc.end()})
}
