import { useEffect, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { downloadQuotePdf, getAdminCustomer, getAdminQuoteMessages, getCustomerQuotes, reviewQuoteDeposit, sendAdminQuoteMessage, updateAdminQuote } from '../lib/api'
import { formatPrice } from '../utils/format'
import './CustomerPortal.css'
import './CustomerPortalMobile.css'
import './AdminQuoteWorkspace.css'

const MILESTONE_STATUS = { pending:'Pendiente', in_progress:'En proceso', completed:'Terminado' }

function formatRequestedDate(value) {
  if (!value) return ''
  const text = String(value)
  const date = new Date(/^\d{4}-\d{2}-\d{2}$/.test(text) ? `${text}T00:00:00` : text)
  return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString('es-UY')
}

export default function AdminQuoteWorkspace(){
  const {id,quoteId}=useParams(); const {adminUser,adminToken}=useAuth(); const [customer,setCustomer]=useState(null); const [quote,setQuote]=useState(null); const [messages,setMessages]=useState([]); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  useEffect(()=>{if(!adminToken)return; Promise.all([getAdminCustomer(id,adminToken),getCustomerQuotes(id,adminToken),getAdminQuoteMessages(quoteId,adminToken)]).then(([c,q,m])=>{setCustomer(c);setQuote((q.rows||[]).find(x=>x.id===Number(quoteId)));setMessages(m.rows||[])}).catch(e=>setError(e.message))},[id,quoteId,adminToken])
  if(!adminUser||!adminToken)return <Navigate to={`/admin/login?redirect=/admin/clientes/${id}/cotizaciones/${quoteId}`} replace/>
  async function saveProposal(e){e.preventDefault();setSaving(true);try{setQuote(await updateAdminQuote(quote.id,{...quote,status:quote.status==='in_progress'?'sent':quote.status},adminToken))}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function send(e){e.preventDefault();if(!message.trim())return;try{const m=await sendAdminQuoteMessage(quote.id,{message},adminToken);setMessages(p=>[...p,m]);setMessage('')}catch(e){setError(e.message)}}
  function addMilestone(){setQuote({...quote,milestones:[...(quote.milestones||[]),{id:`milestone-${Date.now()}`,title:'',description:'',status:'pending',plannedStartAt:'',plannedEndAt:'',completedAt:null}]})}
  function updateMilestone(index,updates){setQuote({...quote,milestones:(quote.milestones||[]).map((item,itemIndex)=>itemIndex===index?{...item,...updates}:item)})}
  function removeMilestone(index){setQuote({...quote,milestones:(quote.milestones||[]).filter((_,itemIndex)=>itemIndex!==index)})}
  async function reviewDeposit(status){setSaving(true);setError('');try{setQuote(await reviewQuoteDeposit(quote.id,status,adminToken))}catch(e){setError(e.message)}finally{setSaving(false)}}
  function addDocumentItem(){setQuote({...quote,documentItems:[...(quote.documentItems||[]),{code:String((quote.documentItems||[]).length+1).padStart(2,'0'),description:'',subtotal:''}]})}
  function updateDocumentItem(index,updates){const items=(quote.documentItems||[]).map((item,itemIndex)=>itemIndex===index?{...item,...updates}:item);const subtotal=items.reduce((sum,item)=>sum+Number(item.subtotal||0),0);setQuote({...quote,documentItems:items,totalAmount:Math.round(subtotal*(1+Number(quote.taxRate??22)/100)*100)/100})}
  function removeDocumentItem(index){const items=(quote.documentItems||[]).filter((_,itemIndex)=>itemIndex!==index);const subtotal=items.reduce((sum,item)=>sum+Number(item.subtotal||0),0);setQuote({...quote,documentItems:items,totalAmount:Math.round(subtotal*(1+Number(quote.taxRate??22)/100)*100)/100})}
  function updateTaxRate(value){const subtotal=(quote.documentItems||[]).reduce((sum,item)=>sum+Number(item.subtotal||0),0);setQuote({...quote,taxRate:value,totalAmount:Math.round(subtotal*(1+Number(value||0)/100)*100)/100})}
  async function saveAndDownloadPdf(e){e.preventDefault();setSaving(true);setError('');try{const updated=await updateAdminQuote(quote.id,{...quote,notifyCustomer:false},adminToken);setQuote(updated);await downloadQuotePdf(updated.id,adminToken)}catch(err){setError(err.message)}finally{setSaving(false)}}
  if(!quote)return <section className="customer-portal"><p>{error||'Cargando cotización…'}</p></section>
  return <section className="customer-portal"><header><div><Link to={`/admin/clientes/${id}`}>← Volver al cliente</Link><span>Respuesta comercial</span><h1>{quote.title}</h1><p>{customer?.name} · {quote.referenceNumber}</p></div>{quote.totalAmount>0&&<strong>{formatPrice(quote.totalAmount,quote.currency)}</strong>}</header>{error&&<p className="customer-portal-error">{error}</p>}
    <div className="admin-quote-workspace"><div className="quote-workspace"><div className="quote-workspace-head"><div><span>Solicitud del cliente</span><p>{quote.description}</p>{quote.budget!=null&&<p>Presupuesto indicado: {formatPrice(quote.budget,quote.currency)}</p>}{formatRequestedDate(quote.desiredDate)&&<p>Fecha deseada: {formatRequestedDate(quote.desiredDate)}</p>}</div></div>{quote.attachments?.length>0&&<div className="quote-files">{quote.attachments.map((f,i)=><a key={i} href={f.data} download={f.name}>📎 {f.name}</a>)}</div>}
      <div className="quote-thread">{messages.length===0?<p className="quote-thread-empty">Todavía no hay mensajes.</p>:messages.map(m=><article key={m.id} className={m.authorRole==='admin'?'is-customer':'is-admin'}><small>{m.authorRole==='admin'?'Mercadobra':customer?.name||'Cliente'}</small><p>{m.message}</p><time>{new Date(m.createdAt).toLocaleString('es-UY')}</time></article>)}</div><form className="quote-message-form" onSubmit={send}><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Responder al cliente…"/><button>Enviar mensaje</button></form></div>
      <form className="admin-proposal-form" onSubmit={saveProposal}><span>Propuesta económica</span><h2>Preparar cotización</h2><label>Título<input value={quote.title} onChange={e=>setQuote({...quote,title:e.target.value})}/></label><label>Descripción para el cliente<textarea rows="5" value={quote.proposalDescription||''} onChange={e=>setQuote({...quote,proposalDescription:e.target.value})}/></label><div><label>Monto<input type="number" min="0" value={quote.totalAmount} onChange={e=>setQuote({...quote,totalAmount:e.target.value})}/></label><label>Moneda<select value={quote.currency} onChange={e=>setQuote({...quote,currency:e.target.value})}><option>UYU</option><option>USD</option></select></label></div><label>Estado general<select value={quote.status} onChange={e=>setQuote({...quote,status:e.target.value})}><option value="in_progress">Solicitud recibida</option><option value="sent">Cotización enviada</option><option value="accepted">Presupuesto aprobado</option><option value="project_in_progress">Obra en proceso</option><option value="completed">Trabajo terminado</option><option value="cancelled">Cancelada</option></select></label><label>Inicio estimado<input type="date" value={quote.estimatedStartAt||''} onChange={e=>setQuote({...quote,estimatedStartAt:e.target.value})}/></label><label>Fin estimado<input type="date" value={quote.estimatedEndAt||''} onChange={e=>setQuote({...quote,estimatedEndAt:e.target.value})}/></label><section className="admin-milestones"><header><div><span>Seguimiento de obra</span><h3>Hitos del proyecto</h3></div><button type="button" onClick={addMilestone}>＋ Agregar hito</button></header>{(quote.milestones||[]).length===0?<p>Todavía no hay hitos. Podés agregarlos cuando el presupuesto sea aprobado.</p>:(quote.milestones||[]).map((item,index)=><article key={item.id||index}><label>Etapa<input value={item.title} onChange={e=>updateMilestone(index,{title:e.target.value})} placeholder="Ej: Fabricación" required/></label><label>Nota visible<textarea rows="2" value={item.description||''} onChange={e=>updateMilestone(index,{description:e.target.value})}/></label><div><label>Estado<select value={item.status} onChange={e=>updateMilestone(index,{status:e.target.value,completedAt:e.target.value==='completed'?(item.completedAt||new Date().toISOString()):null})}>{Object.entries(MILESTONE_STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Desde<input type="date" value={item.plannedStartAt||''} onChange={e=>updateMilestone(index,{plannedStartAt:e.target.value})}/></label><label>Hasta<input type="date" value={item.plannedEndAt||''} onChange={e=>updateMilestone(index,{plannedEndAt:e.target.value})}/></label></div><button type="button" onClick={()=>removeMilestone(index)}>Eliminar hito</button></article>)}</section><button disabled={saving}>{saving?'Guardando…':'Guardar y notificar al cliente'}</button></form></div>
    <form className="admin-deposit-config" onSubmit={saveProposal}><span>Cobro de seña</span><h2>Reserva del proyecto</h2><div><label>Modalidad<select value={quote.depositMode||'none'} onChange={e=>setQuote({...quote,depositMode:e.target.value,depositValue:e.target.value==='none'?0:quote.depositValue})}><option value="none">Sin seña</option><option value="percentage">Porcentaje</option><option value="fixed">Monto fijo</option></select></label>{quote.depositMode!=='none'&&<label>{quote.depositMode==='percentage'?'Porcentaje (%)':'Monto fijo'}<input type="number" min="0" max={quote.depositMode==='percentage'?100:undefined} value={quote.depositValue||''} onChange={e=>setQuote({...quote,depositValue:e.target.value})}/></label>}</div>{quote.depositAmount>0&&<p>Seña calculada: <strong>{formatPrice(quote.depositAmount,quote.currency)}</strong> · Estado: {quote.depositStatus}</p>}{quote.depositStatus==='reported'&&<div className="admin-deposit-review"><a href={quote.depositReceipt?.data} download={quote.depositReceipt?.name||'comprobante'}>Ver comprobante</a><button type="button" onClick={()=>reviewDeposit('approved')} disabled={saving}>Confirmar transferencia</button><button type="button" onClick={()=>reviewDeposit('rejected')} disabled={saving}>Rechazar</button></div>}<button disabled={saving}>{saving?'Guardando…':'Guardar configuración de seña'}</button></form>
    <form className="admin-document-builder" onSubmit={saveAndDownloadPdf}><span>Documento comercial</span><header><div><h2>Cotización PDF</h2><p>Documento corto con detalle económico y condiciones esenciales.</p></div><button type="button" onClick={addDocumentItem}>＋ Agregar ítem</button></header><div className="admin-document-items">{(quote.documentItems||[]).map((item,index)=><article key={`${item.code}-${index}`}><input value={item.code||''} onChange={e=>updateDocumentItem(index,{code:e.target.value})} placeholder="Código"/><input value={item.description||''} onChange={e=>updateDocumentItem(index,{description:e.target.value})} placeholder="Descripción del ítem" required/><input type="number" min="0" value={item.subtotal??''} onChange={e=>updateDocumentItem(index,{subtotal:e.target.value})} placeholder="Subtotal sin IVA" required/><button type="button" onClick={()=>removeDocumentItem(index)} aria-label="Eliminar ítem">×</button></article>)}</div><div className="admin-document-grid"><label>IVA (%)<input type="number" min="0" max="100" value={quote.taxRate??22} onChange={e=>updateTaxRate(e.target.value)}/></label><label>Validez (días)<input type="number" min="1" value={quote.documentTerms?.validityDays||30} onChange={e=>setQuote({...quote,documentTerms:{...(quote.documentTerms||{}),validityDays:e.target.value}})}/></label><label className="is-wide">Forma de pago<textarea rows="3" value={quote.documentTerms?.paymentTerms||''} onChange={e=>setQuote({...quote,documentTerms:{...(quote.documentTerms||{}),paymentTerms:e.target.value}})}/></label><label className="is-wide">Plazo de ejecución<textarea rows="2" value={quote.documentTerms?.executionTime||''} onChange={e=>setQuote({...quote,documentTerms:{...(quote.documentTerms||{}),executionTime:e.target.value}})}/></label><label className="is-wide">Garantía<textarea rows="3" value={quote.documentTerms?.warranty||''} onChange={e=>setQuote({...quote,documentTerms:{...(quote.documentTerms||{}),warranty:e.target.value}})}/></label><label className="is-wide">Exclusiones<textarea rows="4" value={quote.documentTerms?.exclusions||''} onChange={e=>setQuote({...quote,documentTerms:{...(quote.documentTerms||{}),exclusions:e.target.value}})}/></label><label className="is-wide">Notas adicionales<textarea rows="3" value={quote.documentTerms?.notes||''} onChange={e=>setQuote({...quote,documentTerms:{...(quote.documentTerms||{}),notes:e.target.value}})}/></label></div><button disabled={saving||!(quote.documentItems||[]).length}>{saving?'Generando…':'Guardar y descargar PDF'}</button></form>
  </section>
}
