import { useEffect, useMemo, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { getAllCustomerQuotes } from '../lib/api'
import { formatPrice } from '../utils/format'
import './AdminCustomerQuotes.css'

const STATUS={in_progress:'En revisión',sent:'Enviada',accepted:'Aceptada',project_in_progress:'En ejecución',completed:'Finalizada',rejected:'Rechazada',cancelled:'Cancelada'}
export default function AdminCustomerQuotes(){const {adminUser,adminToken}=useAuth();const [rows,setRows]=useState([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{if(!adminToken)return;getAllCustomerQuotes(adminToken).then(r=>setRows(r.rows||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[adminToken]);const filtered=useMemo(()=>rows.filter(q=>(status==='all'||q.status===status)&&(!search.trim()||[q.title,q.referenceNumber,q.customerName,q.customerEmail].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())))),[rows,status,search]);const totals=useMemo(()=>({new:rows.filter(q=>q.status==='in_progress').length,sent:rows.filter(q=>q.status==='sent').length,accepted:rows.filter(q=>['accepted','project_in_progress'].includes(q.status)).length}),[rows]);if(!adminUser||!adminToken)return <Navigate to="/admin/login?redirect=/admin/cotizaciones-clientes" replace/>;return <section className="admin-customer-quotes"><header><div><span>Gestión comercial</span><h1>Cotizaciones</h1><p>Solicitudes, propuestas y conversaciones de clientes registrados.</p></div><nav><Link to="/admin/clientes">Clientes</Link><Link to="/admin/productos">Productos</Link><Link to="/admin/pedidos">Pedidos</Link><Link to="/admin/cotizaciones">Consultas web</Link></nav></header><div className="admin-quote-metrics"><div><strong>{rows.length}</strong><span>Total</span></div><div><strong>{totals.new}</strong><span>En revisión</span></div><div><strong>{totals.sent}</strong><span>Esperando respuesta</span></div><div><strong>{totals.accepted}</strong><span>Aceptadas</span></div></div><div className="admin-quote-toolbar"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, empresa o cotización…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option>{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{error&&<p className="admin-quote-error">{error}</p>}{loading?<p>Cargando cotizaciones…</p>:filtered.length===0?<div className="admin-quote-empty"><h2>No hay cotizaciones para mostrar.</h2></div>:<div className="admin-quote-board">{filtered.map(q=><article key={q.id}><div className="admin-quote-id"><span>{q.referenceNumber}</span><small>{q.updatedAt?new Date(q.updatedAt).toLocaleDateString('es-UY'):''}</small></div><div><h2>{q.title}</h2><Link to={`/admin/clientes/${q.customerId}`}>{q.customerName||q.customerEmail}</Link><p>{q.description}</p></div><div className="admin-quote-commercial">{q.totalAmount>0&&<strong>{formatPrice(q.totalAmount,q.currency)}</strong>}<span className={`is-${q.status}`}>{STATUS[q.status]||q.status}</span></div><Link className="admin-quote-open" to={`/admin/clientes/${q.customerId}/cotizaciones/${q.id}`}>Abrir y responder →</Link></article>)}</div>}</section>}
